### ISSUE TITLE
Calculation-prior _ mean

### ISSUE THREAD

**Issue by ykzou9** [cnexah/VA-DepthNet#10]
Hi again! I noticed that you mentioned a rough method for calculating prior_mean in your previous answers. I tried experimenting based on that, but the prior_mean I computed for the NYU dataset is significantly different from the value you provided. I'm curious to know where the issue might be. Here's my code:

import os
import cv2
import numpy as np

def calculate_prior_mean(dataset_path, filenames_file):
    with open(filenames_file, 'r') as file:
        filenames = file.read().splitlines()

    total_log_depths = 0
    total_valid_pixels = 0

    for filename in filenames:
        depth_image_path = os.path.join(dataset_path, filename)  # Assuming filenames contain paths
        depth_image = cv2.imread(depth_image_path, cv2.IMREAD_UNCHANGED).astype(np.float32) / 1000.0  # Assuming depth values are in millimeters
        valid_pixels = depth_image > 0
        log_depths = np.log(depth_image[valid_pixels])
        total_log_depths += np.sum(log_depths)
        total_valid_pixels += np.sum(valid_pixels)
    prior_mean = total_log_depths / total_valid_pixels

    return prior_mean

dataset_path = 'image-depth-estimation/data/nyu2_test'
filenames_file = 'priormeannyutest.txt'
prior_mean = calculate_prior_mean(dataset_path, filenames_file)
print(f'The calculated prior mean is: {prior_mean}')

Output result：
The calculated prior mean is: 0.8990918813373943

**Comment by cnexah** [comment]
Thank you for your interest!
I guess I computed the prior depth using the following code:
https://github.com/Owen-Liuyuxuan/visualDet3D/blob/master/scripts/depth_precompute.py

However, I think the exact value is not vert important, as long as it is resonable.

**Comment by ykzou9** [comment]
> Thank you for your interest! I guess I computed the prior depth using the following code: https://github.com/Owen-Liuyuxuan/visualDet3D/blob/master/scripts/depth_precompute.py
> 
> However, I think the exact value is not vert important, as long as it is resonable.

Sure thing! Thanks for your guidance. I'll dig deeper into it.
