### ISSUE TITLE
Need some help please

### ISSUE THREAD

**Issue by abdkhanstd** [cnexah/VA-DepthNet#2]
Can you please point out where can I find the GT for KITTI RAW data . 

Much appreciated, 
Thank you.

**Comment by cnexah** [comment]
https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

**Comment by abdkhanstd** [comment]
> https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

Thank you. Much appriciated
